[tool.poetry]
name = "routine-lab"
version = "0.1.0"
description = ""
authors = ["Andre Araujo"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyautogui = "^0.9.54"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
